// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDOEJYP78u7QXdAXbItxrgEkOk0008sY',
    appId: '1:713581331205:web:bada816273c0b1ec78ed6c',
    messagingSenderId: '713581331205',
    projectId: 'sieera-marketplace-69eaa',
    authDomain: 'sieera-marketplace-69eaa.firebaseapp.com',
    storageBucket: 'sieera-marketplace-69eaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBYJDkxKRSk0akxWlTJyfM4ONvyWy0Yw',
    appId: '1:713581331205:android:b6b04a6dd43b014378ed6c',
    messagingSenderId: '713581331205',
    projectId: 'sieera-marketplace-69eaa',
    storageBucket: 'sieera-marketplace-69eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVeryqMEvkOEHOtIcuSAGqc2NG57emi0s',
    appId: '1:713581331205:ios:a6ae2c57b01db19078ed6c',
    messagingSenderId: '713581331205',
    projectId: 'sieera-marketplace-69eaa',
    storageBucket: 'sieera-marketplace-69eaa.firebasestorage.app',
    iosBundleId: 'com.example.testingAplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVeryqMEvkOEHOtIcuSAGqc2NG57emi0s',
    appId: '1:713581331205:ios:a6ae2c57b01db19078ed6c',
    messagingSenderId: '713581331205',
    projectId: 'sieera-marketplace-69eaa',
    storageBucket: 'sieera-marketplace-69eaa.firebasestorage.app',
    iosBundleId: 'com.example.testingAplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtDOEJYP78u7QXdAXbItxrgEkOk0008sY',
    appId: '1:713581331205:web:eed9175355f5607178ed6c',
    messagingSenderId: '713581331205',
    projectId: 'sieera-marketplace-69eaa',
    authDomain: 'sieera-marketplace-69eaa.firebaseapp.com',
    storageBucket: 'sieera-marketplace-69eaa.firebasestorage.app',
  );
}
